[WIP] branch name action
wizardoc/commitlint-wizardoc pull request #13
Opened 2021-05-31 13:22 UTC by z825316969

2021-06-04 07:09 UTC, youncccat commented on .github/shell/branch-name.sh
> +branchType="feature|hotfix|improve|chore"
下划线命名

2021-06-04 07:14 UTC, youncccat requested changes

2021-06-04 07:14 UTC, youncccat commented on .github/shell/branch-name.sh
> +then
风格问题，保持 if [[  ]];then 的写法

2021-06-04 07:14 UTC, youncccat commented
shell 和 tests 放在一个文件夹下，搞成一个叫 ci 的子包

2021-06-04 07:21 UTC, z825316969 commented on .github/shell/branch-name.sh
> +then
It is solved

2021-06-04 07:22 UTC, z825316969 commented on .github/shell/branch-name.sh
> +branchType="feature|hotfix|improve|chore"
It is solved

2021-06-04 07:24 UTC, z825316969 commented
在packages下?

2024-02-19 17:12 UTC, mistricky commented
This PR is stale, so closed

2024-02-19 17:12 UTC, closed without merging